### ISSUE TITLE
Python may not be configured for Tk

### ISSUE THREAD

**Issue by CONSULitAS** [tomoyanonymous/homebrew-flatcam#10]
@tomoyanonymous Thanks a lot for this.

Since `brew install flatcam` does not work for me, I tried `brew install flatcam-beta`.

The process ends successfully, but starting the installed result leads to
```
$ flatcam
Traceback (most recent call last):
  File "/usr/local/bin/flatcam", line 7, in <module>
    from app_Main import App
  File "/usr/local/Cellar/flatcam-beta/8.9.9/libexec/app_Main.py", line 63, in <module>
    from appObjects.ObjectCollection import *
  File "/usr/local/Cellar/flatcam-beta/8.9.9/libexec/appObjects/ObjectCollection.py", line 25, in <module>
    from appObjects.FlatCAMScript import ScriptObject
  File "/usr/local/Cellar/flatcam-beta/8.9.9/libexec/appObjects/FlatCAMScript.py", line 17, in <module>
    import tkinter as tk
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

Auntie google didn't help that much. Could you perhaps help? Any ideas?

Thanks in advance.

**Comment by CONSULitAS** [comment]
Heureka!

Hints found here: https://gist.github.com/iexa/2ac761bfd96ab78988b76c030d54a5b8#file-python-with-tcl-rb

https://gist.github.com/iexa/2ac761bfd96ab78988b76c030d54a5b8#gistcomment-3637901 leads to
https://github.com/Homebrew/homebrew-core/commit/e41f89603eeb6e63ca36d189b1fc8248e275f2c6#diff-38ae209ebc6d2954d5532ae8c3e6e579dc77a7d3002bed515fa930d6ea528139

Updating this file manually and `HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade --build-from-source python@3.9` did the trick.

But it is not clear to me, why homebrew doesn't upgrade the rb file!

**Comment by CONSULitAS** [comment]
BTW: discussions here https://mig8447.github.io/manufacturing/electronics/flatcam/2020/03/13/flatcam-beta-8.96-installation-in-macos-mojave-10.14.html#comment-5321789670

**Comment by tomoyanonymous** [comment]
Hi, what is your OS version? In my environment(Catalina), the formula still works.

https://github.com/Homebrew/homebrew-core/blob/ae44bb74b54a360e0611e5c8c33af0c4108bfc43/Formula/python%403.9.rb#L448-L449

In the latest `python3.9` formula, it seems that tkinter for python can be installed through `python-tk`. Maybe we needed to update dependencies.

**Comment by tomoyanonymous** [comment]
**For the temporary workaround: you need to do `brew update && brew install python-tk`**

 https://github.com/Homebrew/homebrew-core/commit/80412c280721d4a904e3492635f24c98d173dc9d#diff-38ae209ebc6d2954d5532ae8c3e6e579dc77a7d3002bed515fa930d6ea528139  
 I found that the change above was applied just 4 days ago, it seems that the commit caused the problem.

After I did `brew update` and tested `python3 -m tkinter`, it showed the same error message as you pasted.
Then I installed tkinter with `brew install python-tk` and both of `python3 -m tkinter` and `flatcam` command started working properly. 

I will update the formula soon.

Also, note that solutions that modify the formula file manually temporarily solves the problem but it will be overwritten by homebrew itself once `brew update` is run (regardless explicitly or implicitly by executing `brew install something`)

**Comment by tomoyanonymous** [comment]
The formula has been updated now. Please try it again

**Comment by CONSULitAS** [comment]
@tomoyanonymous 

> Hi, what is your OS version?
Hi, it is: 10.14.6 Mojave

> For the temporary workaround:
Thanks for the support with lightning speed. 👍 😄 

> brew update && brew install python-tk
Works with no error and leads to a new message after start of Flatcam (on Terminal):

![Bildschirmfoto 2021-03-31 um 11 27 43](https://user-images.githubusercontent.com/6808242/113122660-21dc0280-9214-11eb-985c-ba4b71fbfc60.png)

> python3 -m tkinter
Doesn't throw any error. Fine!
 
FlatCAM 8.994 ist still working. 👍 

Seems to me that this works!

Thanks a lot.
