### ISSUE TITLE
Error: Your Command Line Tools are too outdated

### ISSUE THREAD

**Issue by atomino-max** [tomoyanonymous/homebrew-flatcam#14]
I have Big Sur 11.6 and Xcode 13.1, and I cannot find the way to install Flatcam see below :

HEAD is now at d4f94133 Merged in Beta (pull request #344)
==> Installing flatcam-beta from tomoyanonymous/flatcam
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.0.

max@macMax:~$ softwareupdate --all --install --force
Software Update Tool

Finding available software
No updates are available.
max@macMax:~$ flatcam
zsh: command not found: flatcam

**Comment by atomino-max** [comment]
I try also with 
brew upgrade flatcam-beta
and I have the same error.

**Comment by tomoyanonymous** [comment]
Did you try the secondary suggestion?

```sh
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install
```

`softwareupdate` command sometimes fails to find CLT updates as reported the link below.

https://adrianmoreno.com/2020/11/15/get-homebrew-working-with-macos-11-big-sur.html

**Comment by atomino-max** [comment]
You are right !!!
Now it's working.
Thanks a lot.
Max
