### ISSUE TITLE
unable to install or tools

### ISSUE THREAD

**Issue by swaxolez** [tomoyanonymous/homebrew-flatcam#15]
ERROR: Could not find a version that satisfies the requirement ortools>=7.0 (from versions: none)

on a Macbook pro m1

**Comment by tomoyanonymous** [comment]
The same issue was discussed on this thread today.

https://gist.github.com/natevw/3e6fc929aff358b38c0a?permalink_comment_id=4055514#gistcomment-4055514

> Ortools is a library maintained by Google, though open-sourced. Problem is - there is no build for Mac M1 arch. Me guessing You would have big troubles building it from source yourself. Best thing to do: give up native approach - use VM/linux.

Also this kind of workaround may work. Running `brew` itself via `arch -x86_64` or launching terminal with an option of "Open with Rosetta" from a "get info" in right-click menu in the application.

https://gist.github.com/progrium/b286cd8c82ce0825b2eb3b0b3a0720a0

**Comment by tomoyanonymous** [comment]
I recently got my own M1 Macbook Air and tried to build flatcam and it worked (0555a0013b0f16e13ce2e6d368d6d2abe4181d97).
Both x86_64 and arm64 build are working now.

The problem of ortools on pip for M1 processor looks solved but I don't know what made it.

<img width="983" alt="スクリーンショット 2023-06-21 20 16 27" src="https://github.com/tomoyanonymous/homebrew-flatcam/assets/7259276/c11b6a8f-b150-49f5-b5e3-400cc6958736">
