### ISSUE TITLE
Vispy 0.7 not working on Mac arm64

### ISSUE THREAD

**Issue by epideme** [tomoyanonymous/homebrew-flatcam#16]
Thanks for all your effort on this project.

Running flatcam-beta causes an arm64 specific issue on M1 Macs related to vispy<=0.7.

  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x4762c1898, class_getMethodImplementation_stret): symbol not found

Running "/opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/bin/pip3 install vispy==0.7.1" fixes the issue. 
Latest vispy has all new, shiny, modern issues but 0.7.1 seems fine for me.

**Comment by tomoyanonymous** [comment]
Thanks for reporting! I will make PR for fixing it.
