### ISSUE TITLE
Flatcam Beta, MacBook Pro M2, MacOS 13.3

### ISSUE THREAD

**Issue by Andretti1967** [tomoyanonymous/homebrew-flatcam#18]
Hi 
Trying to install Flatcam Beta on my MacBook Pro M2, MacOS 13.3

==> /opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/bin/pip install descartes
==> /opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/bin/pip install -r requirements.txt
Last 15 lines from /Users/andres/Library/Logs/Homebrew/flatcam-beta/03.pip:
          raise UserException(
      sipbuild.exceptions.UserException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python3.11 -m pip install --upgrade pip

Any idea?
Thanks in advance.
Andres

**Comment by Andretti1967** [comment]
FYI, under arch -x86_64 it works.
Best regards.
Andres

**Comment by tomoyanonymous** [comment]
I can not confirm the issue because I do not have M1 arch machine now, but maybe problem around vispy?

https://gist.github.com/natevw/3e6fc929aff358b38c0a?permalink_comment_id=4055555#gistcomment-4055555

If it works on `arch -x86_64` without problem, I recommend to keep using it.
