### ISSUE TITLE
3D Plot of Gerber Files Missing

### ISSUE THREAD

**Issue by benortiz** [tomoyanonymous/homebrew-flatcam#19]
I've installed flatcam beta and it almost all works as expected. Plotting drill files works, but when I plot a gerber file, nothing appears on the canvas. Curiously, the outline is selectable and clearly there, but none of the details from the file/traces. 

I've tried enabling / disabling the plot. The logs don't appear to indicate anything obviously wrong, but I'll include them here anyway.

<details><summary>3D Logs</summary>
<pre>
[DEBUG][Dummy-4] open_gerber()
[DEBUG][Dummy-4] AppObject.new_object()
[DEBUG][Dummy-4] Calling object constructor...
[DEBUG][Dummy-4] FlatCAMObj.visible()
[DEBUG][Dummy-4] 0.082591 seconds before initialize().
[WARNING][Dummy-4] Line ignored (1): %TF.GenerationSoftware,KiCad,Pcbnew,7.0.2-0*%
[WARNING][Dummy-4] Line ignored (2): %TF.CreationDate,2023-05-11T20:33:04-07:00*%
[WARNING][Dummy-4] Line ignored (3): %TF.ProjectId,EL146-Amp,454c3134-362d-4416-9d70-2e6b69636164,rev?*%
[WARNING][Dummy-4] Line ignored (4): %TF.SameCoordinates,PX17d7840PY7735940*%
[WARNING][Dummy-4] Line ignored (5): %TF.FileFunction,Copper,L2,Bot*%
[WARNING][Dummy-4] Line ignored (6): %TF.FilePolarity,Positive*%
[DEBUG][Dummy-4] Gerber format found. (%FSLAX46Y46*%) 
[DEBUG][Dummy-4] Gerber format found. Gerber zeros = L (L-omit leading zeros, T-omit trailing zeros, D-no zero supression)
[DEBUG][Dummy-4] Gerber format found. Coordinates type = Absolute (Absolute or Relative)
[DEBUG][Dummy-4] Gerber units found = MM
[WARNING][Dummy-4] Line ignored (15): %TA.AperFunction,NonConductor*%
[WARNING][Dummy-4] Line ignored (17): %TD*%
[WARNING][Dummy-4] Line ignored (19): %TA.AperFunction,NonConductor*%
[WARNING][Dummy-4] Line ignored (21): %TD*%
[WARNING][Dummy-4] Line ignored (22): %TA.AperFunction,ComponentPad*%
[WARNING][Dummy-4] Line ignored (24): %TD*%
[WARNING][Dummy-4] Line ignored (25): %TA.AperFunction,ComponentPad*%
[WARNING][Dummy-4] Line ignored (27): %TD*%
[WARNING][Dummy-4] Line ignored (28): %TA.AperFunction,ComponentPad*%
[WARNING][Dummy-4] Line ignored (30): %TD*%
[WARNING][Dummy-4] Line ignored (31): %TA.AperFunction,ComponentPad*%
[WARNING][Dummy-4] Line ignored (33): %TD*%
[WARNING][Dummy-4] Line ignored (34): %TA.AperFunction,ComponentPad*%
[WARNING][Dummy-4] Line ignored (36): %TD*%
[WARNING][Dummy-4] Line ignored (37): %TA.AperFunction,ComponentPad*%
[WARNING][Dummy-4] Line ignored (39): %TD*%
[WARNING][Dummy-4] Line ignored (40): %TA.AperFunction,ComponentPad*%
[WARNING][Dummy-4] Line ignored (42): %TD*%
[WARNING][Dummy-4] Line ignored (43): %TA.AperFunction,ComponentPad*%
[WARNING][Dummy-4] Line ignored (45): %TD*%
[WARNING][Dummy-4] Line ignored (46): %TA.AperFunction,ComponentPad*%
[WARNING][Dummy-4] Line ignored (48): %TD*%
[WARNING][Dummy-4] Line ignored (49): %TA.AperFunction,ComponentPad*%
[WARNING][Dummy-4] Line ignored (51): %TD*%
[WARNING][Dummy-4] Line ignored (52): %TA.AperFunction,Conductor*%
[WARNING][Dummy-4] Line ignored (54): %TD*%
[WARNING][Dummy-4] Line ignored (463): %TO.P,IC1,1,N.C._1*%
[WARNING][Dummy-4] Line ignored (464): %TO.N,unconnected-(IC1-N.C._1-Pad1)*%
[WARNING][Dummy-4] Line ignored (467): %TO.P,IC1,2,VP*%
[WARNING][Dummy-4] Line ignored (468): %TO.N,Net-(IC1-VP)*%
[WARNING][Dummy-4] Line ignored (470): %TO.P,IC1,3,VI*%
[WARNING][Dummy-4] Line ignored (471): %TO.N,Net-(IC1-VI)*%
[WARNING][Dummy-4] Line ignored (473): %TO.P,IC1,4,GND1*%
[WARNING][Dummy-4] Line ignored (474): %TO.N,GND*%
[WARNING][Dummy-4] Line ignored (476): %TO.P,IC1,5,VC*%
[WARNING][Dummy-4] Line ignored (477): %TO.N,Net-(IC1-VC)*%
[WARNING][Dummy-4] Line ignored (479): %TO.P,IC1,6,OUT+*%
[WARNING][Dummy-4] Line ignored (480): %TO.N,Net-(IC1-OUT-)*%
[WARNING][Dummy-4] Line ignored (482): %TO.P,IC1,7,GND2*%
[WARNING][Dummy-4] Line ignored (483): %TO.N,GND*%
[WARNING][Dummy-4] Line ignored (485): %TO.P,IC1,8,OUT-*%
[WARNING][Dummy-4] Line ignored (486): %TO.N,Net-(IC1-OUT+)*%
[WARNING][Dummy-4] Line ignored (488): %TO.P,IC1,9,N.C._2*%
[WARNING][Dummy-4] Line ignored (489): %TO.N,unconnected-(IC1-N.C._2-Pad9)*%
[WARNING][Dummy-4] Line ignored (491): %TD*%
[WARNING][Dummy-4] Line ignored (493): %TO.P,C1,1*%
[WARNING][Dummy-4] Line ignored (494): %TO.N,Net-(C1-Pad1)*%
[WARNING][Dummy-4] Line ignored (496): %TO.P,C1,2*%
[WARNING][Dummy-4] Line ignored (497): %TO.N,Net-(IC1-VI)*%
[WARNING][Dummy-4] Line ignored (499): %TD*%
[WARNING][Dummy-4] Line ignored (501): %TO.P,J1,T*%
[WARNING][Dummy-4] Line ignored (502): %TO.N,Net-(C1-Pad1)*%
[WARNING][Dummy-4] Line ignored (504): %TO.P,J1,TN*%
[WARNING][Dummy-4] Line ignored (505): %TO.N,N/C*%
[WARNING][Dummy-4] Line ignored (507): %TD*%
[WARNING][Dummy-4] Line ignored (509): %TO.P,C2,1*%
[WARNING][Dummy-4] Line ignored (510): %TO.N,GND*%
[WARNING][Dummy-4] Line ignored (512): %TO.P,C2,2*%
[WARNING][Dummy-4] Line ignored (513): %TO.N,Net-(IC1-VC)*%
[WARNING][Dummy-4] Line ignored (515): %TD*%
[WARNING][Dummy-4] Line ignored (517): %TO.P,SW1,1,CW*%
[WARNING][Dummy-4] Line ignored (518): %TO.N,Net-(SW1-CW)*%
[WARNING][Dummy-4] Line ignored (520): %TO.P,SW1,2,W*%
[WARNING][Dummy-4] Line ignored (521): %TO.N,GND*%
[WARNING][Dummy-4] Line ignored (523): %TO.P,SW1,3,CCW*%
[WARNING][Dummy-4] Line ignored (525): %TO.P,SW1,4,V+*%
[WARNING][Dummy-4] Line ignored (526): %TO.N,Net-(IC1-VP)*%
[WARNING][Dummy-4] Line ignored (528): %TO.P,SW1,5,V-*%
[WARNING][Dummy-4] Line ignored (529): %TO.N,Net-(BT1-+)*%
[WARNING][Dummy-4] Line ignored (531): %TD*%
[WARNING][Dummy-4] Line ignored (533): %TO.P,LS1,1*%
[WARNING][Dummy-4] Line ignored (534): %TO.N,Net-(IC1-OUT+)*%
[WARNING][Dummy-4] Line ignored (536): %TO.P,LS1,2*%
[WARNING][Dummy-4] Line ignored (537): %TO.N,Net-(IC1-OUT-)*%
[WARNING][Dummy-4] Line ignored (539): %TD*%
[WARNING][Dummy-4] Line ignored (541): %TO.P,R1,1*%
[WARNING][Dummy-4] Line ignored (542): %TO.N,Net-(SW1-CW)*%
[WARNING][Dummy-4] Line ignored (545): %TO.P,R1,2*%
[WARNING][Dummy-4] Line ignored (546): %TO.N,Net-(IC1-VC)*%
[WARNING][Dummy-4] Line ignored (548): %TD*%
[WARNING][Dummy-4] Line ignored (550): %TO.P,BT1,1,+*%
[WARNING][Dummy-4] Line ignored (551): %TO.N,Net-(BT1-+)*%
[WARNING][Dummy-4] Line ignored (554): %TO.P,BT1,2,-*%
[WARNING][Dummy-4] Line ignored (555): %TO.N,GND*%
[WARNING][Dummy-4] Line ignored (557): %TD*%
[WARNING][Dummy-4] Line ignored (559): %TO.N,Net-(C1-Pad1)*%
[WARNING][Dummy-4] Line ignored (564): %TO.N,Net-(IC1-VI)*%
[WARNING][Dummy-4] Line ignored (571): %TO.N,Net-(IC1-VC)*%
[WARNING][Dummy-4] Line ignored (580): %TO.N,Net-(IC1-VP)*%
[WARNING][Dummy-4] Line ignored (593): %TO.N,Net-(IC1-OUT+)*%
[WARNING][Dummy-4] Line ignored (600): %TO.N,Net-(IC1-OUT-)*%
[WARNING][Dummy-4] Line ignored (607): %TO.N,Net-(BT1-+)*%
[WARNING][Dummy-4] Line ignored (614): %TO.N,Net-(SW1-CW)*%
[WARNING][Dummy-4] Line ignored (623): %TD*%
[WARNING][Dummy-4] Line ignored (624): %TA.AperFunction,Conductor*%
[WARNING][Dummy-4] Line ignored (625): %TO.N,GND*%
[WARNING][Dummy-4] Line ignored (3495): %TD.AperFunction*%
[WARNING][Dummy-4] Line ignored (3496): %TD*%
[WARNING][Dummy-4] Joining 256 polygons.
[DEBUG][Dummy-4] Union by buffer...
[WARNING][Dummy-4] Union(buffer) done.
[DEBUG][Dummy-4] New object with name: EL146-Amp-B_Cu.gbr. 0.503810 seconds executing initialize().
[DEBUG][Dummy-4] parseGerber.Gerber.bounds()
[DEBUG][Dummy-4] Moving new object back to main thread.
[DEBUG][MainThread] on_object_created()
[DEBUG][MainThread] on_object_created --> OC.append()
[DEBUG][MainThread] GerberObject.set_ui()
[DEBUG][MainThread] set_ui --> FlatCAMObj.to_form()
[DEBUG][MainThread] build_ui--> FlatCAMObj.build_ui()
[DEBUG][MainThread] register_recent()
[DEBUG][MainThread]    gerber
[DEBUG][MainThread]    /Users/benortiz/Library/Mobile Documents/com~apple~CloudDocs/School/EL 146/EL146-Amp/Outputs/EL146-Amp-B_Cu.gbr
[DEBUG][Dummy-5] plotting_task --> GerberObject.plot()
[DEBUG][Dummy-5] plot --> FlatCAMObj.plot()
[DEBUG][Dummy-5] 0.643879 seconds adding object and plotting.
</pre>
</details>

I also tried switching to the 2D canvas, but that hits an error that causes the program to crash. I'm not worried about solving this in this issue, but I thought I would include it in case it helps track down what's going on.

<details><summary>2D Logs</summary>
<pre>
[DEBUG][Dummy-4] open_gerber()
[DEBUG][Dummy-4] AppObject.new_object()
[DEBUG][Dummy-4] Calling object constructor...
[DEBUG][Dummy-4] FlatCAMObj.visible()
[DEBUG][Dummy-4] 0.083515 seconds before initialize().
[WARNING][Dummy-4] Line ignored (1): %TF.GenerationSoftware,KiCad,Pcbnew,7.0.2-0*%
[WARNING][Dummy-4] Line ignored (2): %TF.CreationDate,2023-05-11T20:33:04-07:00*%
[WARNING][Dummy-4] Line ignored (3): %TF.ProjectId,EL146-Amp,454c3134-362d-4416-9d70-2e6b69636164,rev?*%
[WARNING][Dummy-4] Line ignored (4): %TF.SameCoordinates,PX17d7840PY7735940*%
[WARNING][Dummy-4] Line ignored (5): %TF.FileFunction,Copper,L2,Bot*%
[WARNING][Dummy-4] Line ignored (6): %TF.FilePolarity,Positive*%
[DEBUG][Dummy-4] Gerber format found. (%FSLAX46Y46*%) 
[DEBUG][Dummy-4] Gerber format found. Gerber zeros = L (L-omit leading zeros, T-omit trailing zeros, D-no zero supression)
[DEBUG][Dummy-4] Gerber format found. Coordinates type = Absolute (Absolute or Relative)
[DEBUG][Dummy-4] Gerber units found = MM
[WARNING][Dummy-4] Line ignored (15): %TA.AperFunction,NonConductor*%
[WARNING][Dummy-4] Line ignored (17): %TD*%
[WARNING][Dummy-4] Line ignored (19): %TA.AperFunction,NonConductor*%
[WARNING][Dummy-4] Line ignored (21): %TD*%
[WARNING][Dummy-4] Line ignored (22): %TA.AperFunction,ComponentPad*%
[WARNING][Dummy-4] Line ignored (24): %TD*%
[WARNING][Dummy-4] Line ignored (25): %TA.AperFunction,ComponentPad*%
[WARNING][Dummy-4] Line ignored (27): %TD*%
[WARNING][Dummy-4] Line ignored (28): %TA.AperFunction,ComponentPad*%
[WARNING][Dummy-4] Line ignored (30): %TD*%
[WARNING][Dummy-4] Line ignored (31): %TA.AperFunction,ComponentPad*%
[WARNING][Dummy-4] Line ignored (33): %TD*%
[WARNING][Dummy-4] Line ignored (34): %TA.AperFunction,ComponentPad*%
[WARNING][Dummy-4] Line ignored (36): %TD*%
[WARNING][Dummy-4] Line ignored (37): %TA.AperFunction,ComponentPad*%
[WARNING][Dummy-4] Line ignored (39): %TD*%
[WARNING][Dummy-4] Line ignored (40): %TA.AperFunction,ComponentPad*%
[WARNING][Dummy-4] Line ignored (42): %TD*%
[WARNING][Dummy-4] Line ignored (43): %TA.AperFunction,ComponentPad*%
[WARNING][Dummy-4] Line ignored (45): %TD*%
[WARNING][Dummy-4] Line ignored (46): %TA.AperFunction,ComponentPad*%
[WARNING][Dummy-4] Line ignored (48): %TD*%
[WARNING][Dummy-4] Line ignored (49): %TA.AperFunction,ComponentPad*%
[WARNING][Dummy-4] Line ignored (51): %TD*%
[WARNING][Dummy-4] Line ignored (52): %TA.AperFunction,Conductor*%
[WARNING][Dummy-4] Line ignored (54): %TD*%
[WARNING][Dummy-4] Line ignored (463): %TO.P,IC1,1,N.C._1*%
[WARNING][Dummy-4] Line ignored (464): %TO.N,unconnected-(IC1-N.C._1-Pad1)*%
[WARNING][Dummy-4] Line ignored (467): %TO.P,IC1,2,VP*%
[WARNING][Dummy-4] Line ignored (468): %TO.N,Net-(IC1-VP)*%
[WARNING][Dummy-4] Line ignored (470): %TO.P,IC1,3,VI*%
[WARNING][Dummy-4] Line ignored (471): %TO.N,Net-(IC1-VI)*%
[WARNING][Dummy-4] Line ignored (473): %TO.P,IC1,4,GND1*%
[WARNING][Dummy-4] Line ignored (474): %TO.N,GND*%
[WARNING][Dummy-4] Line ignored (476): %TO.P,IC1,5,VC*%
[WARNING][Dummy-4] Line ignored (477): %TO.N,Net-(IC1-VC)*%
[WARNING][Dummy-4] Line ignored (479): %TO.P,IC1,6,OUT+*%
[WARNING][Dummy-4] Line ignored (480): %TO.N,Net-(IC1-OUT-)*%
[WARNING][Dummy-4] Line ignored (482): %TO.P,IC1,7,GND2*%
[WARNING][Dummy-4] Line ignored (483): %TO.N,GND*%
[WARNING][Dummy-4] Line ignored (485): %TO.P,IC1,8,OUT-*%
[WARNING][Dummy-4] Line ignored (486): %TO.N,Net-(IC1-OUT+)*%
[WARNING][Dummy-4] Line ignored (488): %TO.P,IC1,9,N.C._2*%
[WARNING][Dummy-4] Line ignored (489): %TO.N,unconnected-(IC1-N.C._2-Pad9)*%
[WARNING][Dummy-4] Line ignored (491): %TD*%
[WARNING][Dummy-4] Line ignored (493): %TO.P,C1,1*%
[WARNING][Dummy-4] Line ignored (494): %TO.N,Net-(C1-Pad1)*%
[WARNING][Dummy-4] Line ignored (496): %TO.P,C1,2*%
[WARNING][Dummy-4] Line ignored (497): %TO.N,Net-(IC1-VI)*%
[WARNING][Dummy-4] Line ignored (499): %TD*%
[WARNING][Dummy-4] Line ignored (501): %TO.P,J1,T*%
[WARNING][Dummy-4] Line ignored (502): %TO.N,Net-(C1-Pad1)*%
[WARNING][Dummy-4] Line ignored (504): %TO.P,J1,TN*%
[WARNING][Dummy-4] Line ignored (505): %TO.N,N/C*%
[WARNING][Dummy-4] Line ignored (507): %TD*%
[WARNING][Dummy-4] Line ignored (509): %TO.P,C2,1*%
[WARNING][Dummy-4] Line ignored (510): %TO.N,GND*%
[WARNING][Dummy-4] Line ignored (512): %TO.P,C2,2*%
[WARNING][Dummy-4] Line ignored (513): %TO.N,Net-(IC1-VC)*%
[WARNING][Dummy-4] Line ignored (515): %TD*%
[WARNING][Dummy-4] Line ignored (517): %TO.P,SW1,1,CW*%
[WARNING][Dummy-4] Line ignored (518): %TO.N,Net-(SW1-CW)*%
[WARNING][Dummy-4] Line ignored (520): %TO.P,SW1,2,W*%
[WARNING][Dummy-4] Line ignored (521): %TO.N,GND*%
[WARNING][Dummy-4] Line ignored (523): %TO.P,SW1,3,CCW*%
[WARNING][Dummy-4] Line ignored (525): %TO.P,SW1,4,V+*%
[WARNING][Dummy-4] Line ignored (526): %TO.N,Net-(IC1-VP)*%
[WARNING][Dummy-4] Line ignored (528): %TO.P,SW1,5,V-*%
[WARNING][Dummy-4] Line ignored (529): %TO.N,Net-(BT1-+)*%
[WARNING][Dummy-4] Line ignored (531): %TD*%
[WARNING][Dummy-4] Line ignored (533): %TO.P,LS1,1*%
[WARNING][Dummy-4] Line ignored (534): %TO.N,Net-(IC1-OUT+)*%
[WARNING][Dummy-4] Line ignored (536): %TO.P,LS1,2*%
[WARNING][Dummy-4] Line ignored (537): %TO.N,Net-(IC1-OUT-)*%
[WARNING][Dummy-4] Line ignored (539): %TD*%
[WARNING][Dummy-4] Line ignored (541): %TO.P,R1,1*%
[WARNING][Dummy-4] Line ignored (542): %TO.N,Net-(SW1-CW)*%
[WARNING][Dummy-4] Line ignored (545): %TO.P,R1,2*%
[WARNING][Dummy-4] Line ignored (546): %TO.N,Net-(IC1-VC)*%
[WARNING][Dummy-4] Line ignored (548): %TD*%
[WARNING][Dummy-4] Line ignored (550): %TO.P,BT1,1,+*%
[WARNING][Dummy-4] Line ignored (551): %TO.N,Net-(BT1-+)*%
[WARNING][Dummy-4] Line ignored (554): %TO.P,BT1,2,-*%
[WARNING][Dummy-4] Line ignored (555): %TO.N,GND*%
[WARNING][Dummy-4] Line ignored (557): %TD*%
[WARNING][Dummy-4] Line ignored (559): %TO.N,Net-(C1-Pad1)*%
[WARNING][Dummy-4] Line ignored (564): %TO.N,Net-(IC1-VI)*%
[WARNING][Dummy-4] Line ignored (571): %TO.N,Net-(IC1-VC)*%
[WARNING][Dummy-4] Line ignored (580): %TO.N,Net-(IC1-VP)*%
[WARNING][Dummy-4] Line ignored (593): %TO.N,Net-(IC1-OUT+)*%
[WARNING][Dummy-4] Line ignored (600): %TO.N,Net-(IC1-OUT-)*%
[WARNING][Dummy-4] Line ignored (607): %TO.N,Net-(BT1-+)*%
[WARNING][Dummy-4] Line ignored (614): %TO.N,Net-(SW1-CW)*%
[WARNING][Dummy-4] Line ignored (623): %TD*%
[WARNING][Dummy-4] Line ignored (624): %TA.AperFunction,Conductor*%
[WARNING][Dummy-4] Line ignored (625): %TO.N,GND*%
[WARNING][Dummy-4] Line ignored (3495): %TD.AperFunction*%
[WARNING][Dummy-4] Line ignored (3496): %TD*%
[WARNING][Dummy-4] Joining 256 polygons.
[DEBUG][Dummy-4] Union by buffer...
[WARNING][Dummy-4] Union(buffer) done.
[DEBUG][Dummy-4] New object with name: EL146-Amp-B_Cu.gbr. 0.307867 seconds executing initialize().
[DEBUG][Dummy-4] parseGerber.Gerber.bounds()
[DEBUG][Dummy-4] Moving new object back to main thread.
[DEBUG][MainThread] on_object_created()
[DEBUG][MainThread] on_object_created --> OC.append()
[DEBUG][MainThread] GerberObject.set_ui()
[DEBUG][MainThread] set_ui --> FlatCAMObj.to_form()
[DEBUG][MainThread] build_ui--> FlatCAMObj.build_ui()
Traceback (most recent call last):
  File "/usr/local/Cellar/flatcam-beta/8.9.94/libexec/appTools/ToolPunchGerber.py", line 107, in on_object_combo_changed
    grb_obj.mark_shapes.enabled = True
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/flatcam-beta/8.9.94/libexec/appGUI/PlotCanvasLegacy.py", line 1596, in enabled
    self.redraw()
  File "/usr/local/Cellar/flatcam-beta/8.9.94/libexec/appGUI/PlotCanvasLegacy.py", line 1362, in redraw
    self.axes.patches.clear()
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ArtistList' object has no attribute 'clear'
Abort trap: 6
</pre>
</details>

OSX 13.3.1 (a) Intel

Thank you and let me know if I can provide any more detail :)

**Comment by tomoyanonymous** [comment]
This problem seems to be caused by the newer version of `shapely`. 
I pinned the version of shapely by replacing `shapely>=1.7.0` to `shapely==1.8.5` at 0555a0013b0f16e13ce2e6d368d6d2abe4181d97 .

Try `brew reinstall flatcam-beta`.

**Comment by benortiz** [comment]
Wow! Thank you so much for addressing this and your work maintaining this utility :) I was able to get my install working by manually pinning the shapely dependency in homebrews code cache as the install command was running. Using the reinstall command didn't work which led me to notice that none of the inreplace commands in flatcam-beta.rb were working. I'm not sure if I am misunderstanding the behavior of inreplace so I just thought I'd let you know.

**Comment by tomoyanonymous** [comment]
Maybe it's because you pinned shapely manually in `requirements.txt`, the fomula code just replace the text "shapely>=1.7.0" into "shapely==1.8.5". Could you try again after clearing the cache files?

**Comment by benortiz** [comment]
Sorry if that wasn't clear! I pinned it manually _after_ it didn't work. I can try deleting the cache and trying again later today though :) (sorry if this is just a homebrew/user issue!)

**Comment by benortiz** [comment]
Hi! Sorry for the delay. I deleted the files in the cache and tried again--with success! Thank you so much :)
