### ISSUE TITLE
Cannot install on Mac OS Ventura 13.3.1 

### ISSUE THREAD

**Issue by statzern** [tomoyanonymous/homebrew-flatcam#21]
Adding flatcam-evo via homebrew fails, nothing added to Cellar with the following error: 
```
/usr/local/Cellar/flatcam-evo/8.9.95/libexec/bin/pip
install
-r
requirements.txt
```
Other versions fail similarly, flatcam fails due to problew with PyQt4, flatcam_beta fails with something related to the descartes dependency. 
Not sure what to make of the error - not a lot of info.

**Comment by tomoyanonymous** [comment]
Thanks for reporting.

The problem looks related to this PR in Homebrew.
The virtual environment of python during installation no longer contains `pip` by default.
https://github.com/Homebrew/brew/pull/15792

I will fix it soon.
