### ISSUE TITLE
Install via brew failed

### ISSUE THREAD

**Issue by cyba3r** [tomoyanonymous/homebrew-flatcam#23]
Hi,

unfortunely the command "brew install flatcalm-evo" failed with:

└─$ brew install flatcam-evo                                                               
==> Fetching tomoyanonymous/flatcam/flatcam-evo
==> Cloning https://bitbucket.org/marius_stanciu/flatcam_beta.git
Updating /Users/joerg/Library/Caches/Homebrew/flatcam-evo--git
==> Checking out branch Beta_8.995
Already on 'Beta_8.995'
Your branch is up to date with 'origin/Beta_8.995'.
HEAD is now at 97bc4592 - Milling Plugin: when an object has a "tools_mill_tooldia" property set as an object option it is used to set the Tool Dia field
==> Installing flatcam-evo from tomoyanonymous/flatcam
==> python3 -m venv --system-site-packages /opt/homebrew/Cellar/flatcam-evo/8.9.95/libexec
==> /opt/homebrew/Cellar/flatcam-evo/8.9.95/libexec/bin/pip install -r requirements.txt
Last 15 lines from /Users/joerg/Library/Logs/Homebrew/flatcam-evo/02.pip:
          raise Exception(f"Python bindings of GDAL {version} require at least libgdal {version}, but {library_version} was found")
      Exception: Python bindings of GDAL 3.8.3 require at least libgdal 3.8.3, but 3.8.2 was found
      [end of output]

I uninstalled GDAL and start over, but there is no new version of GDAL available....

**Comment by tomoyanonymous** [comment]
It seems that the latest version of gdal (3.8.3) has not released on brew yet.
PR for it has already opened and will be merged soon.

https://github.com/Homebrew/homebrew-core/pull/159378

The problem would be solved when it is merged.
If it's hurry, you should edit `requirements.txt` in the original repo.
https://bitbucket.org/marius_stanciu/flatcam_beta/src/Beta_8.995/requirements.txt

like this:
```diff
- gdal
+  gdal==3.8.2
```
if you install with `--debug` option, you can enter the shell when it fails, and can poke a temporary installation repository.

**Comment by cyba3r** [comment]
Today gda was updated and now everything is working fine!! Thank you very much!
