### ISSUE TITLE
Problem installing flatcam beta 

### ISSUE THREAD

**Issue by brankoto** [tomoyanonymous/homebrew-flatcam#25]
when I run  the "brew install flatcam-beta" command I get:

Warning: No available formula with the name "python3.11" (dependency of tomoyanonymous/flatcam/flatcam-beta). Did you mean python@3.11, python@3.10, python@3.12, python-tk@3.11, python@3.8, python@3.9 or python@3.7?

It seems python3.11 must be changed to python@3.11?

thx

**Comment by tomoyanonymous** [comment]
That looks degradation in the last commit to fix #23 .
Fixed in 0b03b0021b44231440157d4ee904f92c2085b8bc .
