### ISSUE TITLE
Install error MacOS Sonoma

### ISSUE THREAD

**Issue by jvegaf** [tomoyanonymous/homebrew-flatcam#27]
I tried with **flatcam-beta** and **flatcam-evo** but have this error:

```sh
Error: Failed changing dylib ID of /opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/lib/python3.11/site-packages/PIL/.dylibs/libpng16.16.dylib. 
  from /DLC/PIL/.dylibs/libpng16.16.dylib
    to /opt/homebrew/opt/flatcam-beta/libexec/lib/python3.11/site-packages/PIL/.dylibs/libpng16.16.dylib
Error: Failed to fix install linkage
The formula built, but you may encounter issues using it or linking other
formulae against it.
==> Summary
🍺  /opt/homebrew/Cellar/flatcam-beta/8.9.94: 20,883 files, 503.4MB, built in 35 seconds
==> Running `brew cleanup flatcam-beta`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> No outdated dependents to upgrade!
==> Checking for dependents of upgraded formulae...
Disable this behaviour by setting HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Reinstalling 1 dependent with broken linkage from source:
tomoyanonymous/flatcam/flatcam-beta
```

thanks 

Regards

**Comment by kilometers** [comment]
For me, both -beta and -evo were able to run despite this error. Did you try checking brew list or running them afterward?

**Comment by dukicn** [comment]
I got the same error during install on M2 Macbook pro. Flatcam does run but every time I use 'Set origin', flatcam breaks with an error: /opt/homebrew/Cellar/python@3.11/3.11.9_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

Not sure if this is related, but this didn't happen on previous MacBook (Same chip) that installed without any errors.

**Comment by freakmaxi** [comment]
Hey @dukicn 

I had the same problem and I fixed it. You can use FlatCAM from this repo if you want.

https://bitbucket.org/freakmaxi/flatcam/src/Beta_8.995/

It was also crashing after save and exit from every editor, such as Gerber, Excellon, Gcode, Geometry. These are fixed too.

You can create an issue on the repo if you experienced anything else.

Cheers.

**Comment by dukicn** [comment]
Thank you. In the mean time I had another linux box laying around and I am using it without any issues, but will give this one a try.

**Comment by dukicn** [comment]
I tried this, but installation fails with python3 -m pip install -r requirements.txt with the following error:

$ python3 -m pip install -r requirements.txt
Collecting shapely==1.8.5 (from -r requirements.txt (line 21))
  Using cached Shapely-1.8.5.tar.gz (200 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/private/var/folders/2f/54_s4r492jl_l1frcxdsy0zc0000gn/T/pip-build-env-xagiz1wq/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/private/var/folders/2f/54_s4r492jl_l1frcxdsy0zc0000gn/T/pip-build-env-xagiz1wq/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/private/var/folders/2f/54_s4r492jl_l1frcxdsy0zc0000gn/T/pip-build-env-xagiz1wq/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

**Comment by freakmaxi** [comment]
Hello @dukicn 

Would it be possible for you to try with Python 3.11

**Comment by dukicn** [comment]
No, 3.11 is not an option since I have other dependencies on 3.12. If you could try to fix this, it would be great. But for now, linux version runs with no issues so it's not that critical. Most of the things still work on flatcam-evo on Mac OS X, as long as I don't set the origin point. And even for that I use a workaround by setting it in Kicad and exporting gerber files with defined origin. Not ideal, but it works for my use case.

**Comment by freakmaxi** [comment]
Okay, no worries, I'll fix it till the end of the day. :) I'm already working on it. Just try after a couple of hours.

**Comment by Kotdnz** [comment]
Try to install packages one by one and the result will fun you.

**Comment by CONSULitAS** [comment]
@tomoyanonymous 

Any help on this issue? Thanks in advance!

```
Your branch is up to date with 'origin/Beta_8.995'.
HEAD is now at 1ef01840 Merged in Beta_8.995 (pull request #37)
==> Reinstalling tomoyanonymous/flatcam/flatcam-evo 
==> python3.11 -m venv --system-site-packages /opt/homebrew/Cellar/flatcam-evo/8.9.95/libexec
==> /opt/homebrew/Cellar/flatcam-evo/8.9.95/libexec/bin/pip install -r requirements.txt
==> chmod +x /opt/homebrew/Cellar/flatcam-evo/8.9.95/libexec/flatcam.py
==> chmod +x /opt/homebrew/Cellar/flatcam-evo/8.9.95/bin/flatcam-evo
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################### 100.0%
Error: Failed changing dylib ID of /opt/homebrew/Cellar/flatcam-evo/8.9.95/libexec/lib/python3.11/site-packages/PIL/.dylibs/libpng16.16.dylib
  from /DLC/PIL/.dylibs/libpng16.16.dylib
    to /opt/homebrew/opt/flatcam-evo/libexec/lib/python3.11/site-packages/PIL/.dylibs/libpng16.16.dylib
Error: Failed to fix install linkage
The formula built, but you may encounter issues using it or linking other
formulae against it.
==> Summary
🍺  /opt/homebrew/Cellar/flatcam-evo/8.9.95: 28,353 files, 903.9MB, built in 1 minute 7 seconds
```

**Comment by CONSULitAS** [comment]
@tomoyanonymous 

>  I had the same problem and I fixed it. You can use FlatCAM from this repo if you want.
> https://bitbucket.org/freakmaxi/flatcam/src/Beta_8.995/>
> It was also crashing after save and exit from every editor, such as Gerber, Excellon, Gcode, Geometry. These are fixed too.
> You can create an issue on the repo if you experienced anything else.

Perhaps it would be a solution to use this repo?

**Comment by freakmaxi** [comment]
> @tomoyanonymous
> 
> > I had the same problem and I fixed it. You can use FlatCAM from this repo if you want.
> > [https://bitbucket.org/freakmaxi/flatcam/src/Beta_8.995/>](https://bitbucket.org/freakmaxi/flatcam/src/Beta_8.995/%3E)
> > It was also crashing after save and exit from every editor, such as Gerber, Excellon, Gcode, Geometry. These are fixed too.
> > You can create an issue on the repo if you experienced anything else.
> 
> Perhaps it would be a solution to use this repo?

There is no need to use my repo anymore. I've already created a pull request that is merged to the original repo, and Brew is using the latest version of the original repo. Plus, the problem you have is not related to what I fixed.

**Comment by tomoyanonymous** [comment]
@CONSULitAS

I think it could be fixed now at the latest version. Try on it.

Also I added a [Contribution guide](https://github.com/tomoyanonymous/homebrew-flatcam/blob/master/CONTRIBUTING.md) to help updating the formula to the latest revision. If you encounted to problems next time, please try to update this formula by opening Pull Request.

**Comment by CONSULitAS** [comment]
@tomoyanonymous 

> I think it could be fixed now at the latest version. Try on it.

```
==> Installing tomoyanonymous/flatcam/flatcam-evo
==> python3.11 -m venv --system-site-packages /opt/homebrew/Cellar/flatcam-evo/8.9.95/libexec
==> /opt/homebrew/Cellar/flatcam-evo/8.9.95/libexec/bin/pip install --no-binary pillow -r requirements.txt
==> chmod +x /opt/homebrew/Cellar/flatcam-evo/8.9.95/libexec/flatcam.py
==> chmod +x /opt/homebrew/Cellar/flatcam-evo/8.9.95/bin/flatcam
🍺  /opt/homebrew/Cellar/flatcam-evo/8.9.95: 29,350 files, 931.1MB, built in 54 seconds

```

Works now again! Thanks a lot.

I think this issue can be closed now.
