### ISSUE TITLE
Generation CNCJob object out of drill file fails

### ISSUE THREAD

**Issue by Andretti1967** [tomoyanonymous/homebrew-flatcam#30]
Hi 

When I try to generate a Generation CNCJob object  out of a drill file, it fails.
Reason is an initialization issue in the ortools.
--
Object (cncjob) failed because: Couldn't build proto file into descriptor pool: Invalid default '0.5' for field operations_research.sat.SatParameters.clause_cleanup_ratio of type 1   Traceback (most recent call last):
--
CNCJob  generation to of Gerber files for example for milling works.

Thanks for your help.

Andres

**Comment by tomoyanonymous** [comment]
Hi, sorry for the late response. If you're facing same problem, try to update the formula to the latest version and open the issue again with more verbose error report and detailed explanation of your environment (machine and the version OS). Thanks!
