### ISSUE TITLE
Error on ortools by Generate CNCJob object

### ISSUE THREAD

**Issue by Andretti1967** [tomoyanonymous/homebrew-flatcam#32]
Computer I use:
MacBook Pro, Apple M2 Silicon, 24GB RAM, macOS Sequoia 15.1.1

andres:~$brew info flatcam-evo
==> tomoyanonymous/flatcam/flatcam-evo: stable 8.9.95
2D Computer-Aided PCB Manufacturing(Beta-evo)
https://bitbucket.org/marius_stanciu/flatcam_beta
Installed
/opt/homebrew/Cellar/flatcam-evo/8.9.95 (28,657 files, 904.5MB) *
  Built from source on 2024-12-10 at 18:53:44
From: https://github.com/tomoyanonymous/homebrew-flatcam/blob/HEAD/flatcam-evo.rb
==> Dependencies
Build: pkg-config ✔
Required: freetype ✔, gdal ✔, geos ✔, pyqt ✔, python@3.11 ✔, python-tk@3.11 ✔, qpdf ✔, spatialindex ✔

When I try to generate a CNCJob object out of a drill file, it fails.
Reason is an initialization issue in the ortools.

Object (cncjob) failed because: Couldn't build proto file into descriptor pool: Invalid default '0.5' for field operations_research.sat.SatParameters.clause_cleanup_ratio of type 1   Traceback (most recent call last):

CNCJob generation to of Gerber files for example for milling works.

If you need the drl File let me now.

**Comment by tomoyanonymous** [comment]
CNCJob generation for excellon data worked on my environment (M1 MBA 2020, macOS15.1.1).
Here's drill file I generated from KiCad,does it work?

```
M48
; DRILL file {KiCad 5.1.2-f72e74a~84~ubuntu16.04.1} date Sat May 11 12:56:25 2019
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2019-05-11T12:56:25+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,5.1.2-f72e74a~84~ubuntu16.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
T1C0.800
T2C1.200
%
G90
G05
T1
X152.22Y-93.82
X156.78Y-95.8
X152.22Y-91.65
X142.51Y-95.67
X142.49Y-92.25
X147.61Y-93.88
X156.76Y-92.38
X147.61Y-96.05
X147.61Y-91.71
X152.22Y-95.99
T2
X185.697Y-72.76
X195.73Y-72.76
X104.386Y-72.815
X114.419Y-72.815
T0
M30
```

**Comment by Andretti1967** [comment]
Hi

Thanks for feedback.
This is strange, it does not work in my environment, same error as with my file.

I’m not familiar with the brew details and how flatcar is build, I guess it is a version problem with the python libraries.

When I got back with time machine and recover brew from April 2024, it works.

Best regards from Switzerland.

Andres


Am 11.12.2024 um 17:14 schrieb 松浦 知也 Matsuura Tomoya ***@***.***>:



CNCJob generation for excellon data worked on my environment (M1 MBA 2020, macOS15.1.1).
Here's drill file I generated from KiCad,does it work?

M48
; DRILL file {KiCad 5.1.2-f72e74a~84~ubuntu16.04.1} date Sat May 11 12:56:25 2019
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2019-05-11T12:56:25+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,5.1.2-f72e74a~84~ubuntu16.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
T1C0.800
T2C1.200
%
G90
G05
T1
X152.22Y-93.82
X156.78Y-95.8
X152.22Y-91.65
X142.51Y-95.67
X142.49Y-92.25
X147.61Y-93.88
X156.76Y-92.38
X147.61Y-96.05
X147.61Y-91.71
X152.22Y-95.99
T2
X185.697Y-72.76
X195.73Y-72.76
X104.386Y-72.815
X114.419Y-72.815
T0
M30

**Comment by tomoyanonymous** [comment]
Sorry I can't help what I can't reproduce. BTW how did you know that the problem is caused by ortools? `requirements.txt` says that now ortools is optional. 
https://bitbucket.org/marius_stanciu/flatcam_beta/src/1ef01840d00eaad9dbd906832911ef63c0748625/requirements.txt#lines-30

**Comment by Andretti1967** [comment]
I unterstand, thank you anyway, you can close the case.

Am 11.12.2024 um 18:15 schrieb 松浦 知也 Matsuura Tomoya ***@***.***>:

﻿

Sorry I can't help what I can't reproduce. BTW how did you know that the problem is caused by ortools? requirements.txt says that now ortools is optional.
https://bitbucket.org/marius_stanciu/flatcam_beta/src/1ef01840d00eaad9dbd906832911ef63c0748625/requirements.txt#lines-30
