### ISSUE TITLE
Directory '/private/tmp/flatcam-beta--ortools-20201009-92240-xoi6sa/or-tools-7.1' is not installable.

### ISSUE THREAD

**Issue by uenz** [tomoyanonymous/homebrew-flatcam#8]
IInstall on Catalina 10.15.7 fails with following output:
```
Last 15 lines from /Users/asr/Library/Logs/Homebrew/flatcam-beta/18.pip:
    status = self.run(options, args)
  File "/usr/local/Cellar/flatcam-beta/8.5.0/libexec/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/usr/local/Cellar/flatcam-beta/8.5.0/libexec/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 294, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "/usr/local/Cellar/flatcam-beta/8.5.0/libexec/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 316, in get_requirements
    req_to_add = install_req_from_line(
  File "/usr/local/Cellar/flatcam-beta/8.5.0/libexec/lib/python3.8/site-packages/pip/_internal/req/constructors.py", line 409, in install_req_from_line
    parts = parse_req_from_line(name, line_source)
  File "/usr/local/Cellar/flatcam-beta/8.5.0/libexec/lib/python3.8/site-packages/pip/_internal/req/constructors.py", line 326, in parse_req_from_line
    url = _get_url_from_path(p, name)
  File "/usr/local/Cellar/flatcam-beta/8.5.0/libexec/lib/python3.8/site-packages/pip/_internal/req/constructors.py", line 280, in _get_url_from_path
    raise InstallationError(
pip._internal.exceptions.InstallationError: Directory '/private/tmp/flatcam-beta--ortools-20201009-92240-xoi6sa/or-tools-7.1' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
Removed build tracker: '/private/tmp/pip-req-tracker-4k93u0lg'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/tomoyanonymous/homebrew-flatcam/issues
```

**Comment by tomoyanonymous** [comment]
Hi, thanks for reporting the problem. 

Sadly, I could not catch up on recent updates for FlatCAM-beta. Once I tried a few months ago, I could not resolve some dependencies. Maybe, the problem caused by `ortools` and the error messages you posted seems to be caused by `ortools` too.

If you urgently need flatcam, please follow the instruction below for a manual installation.
https://gist.github.com/natevw/3e6fc929aff358b38c0a#gistcomment-3111878

If I have a chance, I will try to update the formula again. 
If you can help to fix errors, these docs are very helpful to write a formula.

https://github.com/Homebrew/brew/blob/master/docs/Python-for-Formula-Authors.md
https://github.com/tdsmith/homebrew-pypi-poet

**Comment by tomoyanonymous** [comment]
Hi @uenz , I quickly updated master branch, could you try it with `brew update&& brew install flatcam-beta`?
Finally, I could not find a way to manage pip dependencies. Especially, `ortools` does not provide installation ways other than using wheel, which is not compatible with homebrew's philosophy(always build from source).
So current formula doing a binary installation for pip dependencies, which should work though it is not allowed in official homebrew repository...

**Comment by uenz** [comment]
Hi, 
thanks for the fast response. I gave it a try but it sill wont work
```
Last 15 lines from /Users/asr/Library/Logs/Homebrew/flatcam-beta/01.pip:
2020-10-09 23:43:21 +0200

/usr/local/Cellar/flatcam-beta/8.5.0/libexec/bin/pip
install
descartes

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core): 
https://github.com/tomoyanonymous/homebrew-flatcam/issues

These open issues may also help:
Directory '/private/tmp/flatcam-beta--ortools-20201009-92240-xoi6sa/or-tools-7.1' is not installable. https://github.com/tomoyanonymous/homebrew-flatcam/issues/8
```
Thanks for the links with the documentation. Ill give it a try the next days. Hope i can help.

**Comment by tomoyanonymous** [comment]
OK、I will try to make github action to make sure what the problem is...

**Comment by tomoyanonymous** [comment]
Also FYI, `brew install flatcam-beta --verbose` will output more detailed information.

**Comment by tomoyanonymous** [comment]
https://github.com/tomoyanonymous/homebrew-flatcam/runs/1235781626?check_suite_focus=true

Now, it seems to be OK. Please try it out again.

**Comment by uenz** [comment]
The last update did the trick! Now it works fine.
Thx uenz
